import type { Metadata } from "next";
import { Crimson_Pro } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

export const crimson = Crimson_Pro({ subsets: ["latin"] });
export const mona = localFont({ src: "../assets/Mona-Sans.woff2" });

export const metadata: Metadata = {
	title: "Daily Brain Bits",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={mona.className + " antialiased bg-background"}>{children}</body>
		</html>
	);
}
