import type { Metadata } from "next";
import { Crimson_Pro } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { Menu } from "@/components/menu";

export const crimson = Crimson_Pro({ subsets: ["latin"], variable: "--font-crimson" });
export const mona = localFont({ src: "../assets/Mona-Sans.woff2", variable: "--font-mona" });

export const metadata: Metadata = {
	title: "Daily Brain Bits",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${crimson.variable} ${mona.variable} bg-primary-100 text-foreground font-body antialiased min-h-screen`}>{children}</body>
		</html>
	);
}
