import type { Metadata } from "next";
import { Crimson_Pro } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

export const crimson = Crimson_Pro({ subsets: ["latin"] });
export const mona = localFont({ src: "../assets/Mona-Sans.woff2" });

export const metadata: Metadata = {
	title: "Daily Brain Bits",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={mona.className + " antialiased bg-background"}>
				<main className="flex min-h-screen flex-col items-center snap-y snap-mandatory ">
					<div className="absolute top-[10%]">
						<img src="logo.svg" className="h-24 " />
					</div>
					{children}
				</main>
			</body>
		</html>
	);
}
